config/routes.rb
Gallery::Application.routes.draw do
  resources :comments

  resources 'supports'
  get "photo/new"
  get "photo/create"
  devise_for :users
  resources :albums do
    resources :photos
  end
  resources :photos
  root 'albums#index'	
    mount Sidekiq::Web, at:'/sidekiq'

  

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user
	has_many :photos
	validates :title, presence: true, uniqueness: true
	#validates_uniqueness_of :title

	validates :user_id, presence: true

	before_save :uppercase_title

	#before_create :aaa

	def uppercase_title
		self.title = self.title.capitalize
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  mount_uploader :photo, PhotoUploader

  attr_accessor :rating

  has_and_belongs_to_many :categories

  #accepts_nested_attributes_for :categories

  def view_categories
  	self.categories.map(&:name).join(", ")
  end

end

app/models/support.rb
class Support
	include ActiveModel::Model
	attr_accessor :subject, :message

	validates_presence_of :subject
	#validates :subject, message: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    
    @album = current_user.albums.build(album_params)
	#OR but not secure
    #@album = Album.new(album_params)
    #@album.user = current_user


    respond_to do |format|
      if @album.save
        #AlbumMailer.notify_user(@album).deliver
        AlbumMailerWorker.perform_async(@album.id)
        
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @album = Album.find params[:album_id]
    @photo = @album.photos
  end

  def new
  	@album = Album.find params[:album_id]
  	@photo = Photo.new
  end

  def show
    #@album = Album.find params[:album_id]
    @photo = Photo.find params[:id]
  end

  def edit
     @photo = Photo.find params[:id]
  end

   def update
    
    @photo = Photo.find params[:id]
    if @photo.update_attributes
      redirect_to photo_path(@photo), notice: 'Photo Updated'
    else
      render :edit
    end
  end


  def create
  	@album = Album.find params[:album_id]
  	@photo = @album.photos.build(photo_params)
  	if @photo.save
  		redirect_to photo_path(@photo), notice: 'Photo Added'
  	else
  		render :new
  	end

  end

  private
  	def photo_params
  		 params.require(:photo).permit(:caption, :description, :photo, :category_ids=>[])
  	end

end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController

	def new
		@support = Support.new
	end

	def index
	end
	def create
		SupportMailer.notify(params[:support]).deliver
		redirect_to new_support_path, notice: 'We will contact you asap.'
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Photo', new_album_photo_path(album) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/comments/_form.html.erb
<%= simple_form_for @comment, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :body %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.body %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @comment.body %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gallery" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Gallery</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/photos/create.html.erb
<h1>Photo#create</h1>
<p>Find me in app/views/photo/create.html.erb</p>

app/views/photos/edit.html.erb
<h1>Add photo for: <%=@album.title %></h1>

<%= form_for([@album, @photo]) do |f| %>
	<p><%= f.label :caption %> <br>
		<%= f.text_field :caption %>
	</p>

	<p><%= f.label :description %> <br>
		<%= f.text_area :description %>
	</p>

	<p><%= f.label :photo %> <br>
		<%= f.file_field :photo %>
	</p>

	<p class="button"><%= f.submit %></p>
<% end %>

app/views/photos/index.html.erb
<h1>Listing photos from album: <%=@album.title %></h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Caption</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photo.each do |photo| %>
      <tr>
        <td><%= image_tag(photo.photo_url(:thumb), :class => "img_preview") %></td>
        <td><%= photo.caption %></td>
        <td><%= photo.description %></td>
        <td><%= link_to 'Edit', edit_album_photo_path(@album,photo) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/photos/new.html.erb
<h1>Add photo for: <%=@album.title %></h1>

<%= simple_form_for([@album, @photo]) do |f| %>
		
	<%= f.input :caption, placeholders: 'Please enter caption' %>
	<%= f.input :description, hint: 'At least 10 words' %>
	<%= f.association :categories, as: :check_boxes %>
	<%= f.input :photo %>
	<%= f.input :rating, collection: 1..10, include_blank: false %>
	<%= f.button :submit %>


<!-- 
	<p><%= f.label :caption %> <br>
		<%= f.text_field :caption %>
	</p>

	<p><%= f.label :description %> <br>
		<%= f.text_area :description %>
	</p>

	<p><%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %> <br>
		<%= f.text_area :description %>
	</p>

	<p><%= f.label :photo %> <br>
		<%= f.file_field :photo %>
	</p>

	<p class="button"><%= f.submit %></p> -->

<% end %>

app/views/photos/show.html.erb
<p>Name: <%= @photo.caption %></p>
<p>Description: <%= @photo.description %></p>
<p>Categories: <%= @photo.view_categories %></p>
<p>Photo: <%= image_tag(@photo.photo_url(:thumb)) %></p>

app/views/shared/_footer.html.erb
<footer>
<h4>&copy; All right Researved</h4>
<footer>

app/views/shared/_header.html.erb
<header id="main">
	<h1>Gallery App</h1>
<% if current_user %>
	<%= "Logged in as : #{current_user.email}" %>
<%= link_to 'Sign out', destroy_user_session_path, :method=>:delete %>
<% else %>
<%= link_to 'Sign in', new_user_session_path %>
<% end %>
</header>

app/views/supports/new.html.erb
<h1> support </h1>

<%= form_for @support do  |f| %>
 <p><%= f.label :subject %><br>
 	<%= f.text_field :subject %> </p>
 	<p><%= f.label :message %> <br>
 		<%= f.text_area :message %></p>
 		<p><%= f.submit "Submit" %> </p>
	<% end %>